### ISSUE TITLE
Bug: resolve-parent

### ISSUE THREAD

**Issue by kaitj** [childmindresearch/styxgraph#7]
### Description

`resolve-parent` does not get passed onto the container (base?) runners. This results in commands using the `resolve-parent` flag in the descriptor to mount the full file path and fail.

### Steps to Reproduce

1. Use graphrunner
2. Run any command with resolve-parent (e.g. `eddy`)

### Expected Results

Should pass `resolve-parent` flag to parent

### Actual Results

Command errors out with a failing to mount error with singularity (and presumably Docker) runners.

**Comment by nx10** [comment]
fixed in 425f0f81d78782e6ae2f41e2db05ab6f23b3d11c
